ponymap
=======

'ponymap' is an experimental network scanner, of alpha quality so far.

Replacing nmap is not the goal, even though it would be rather very nice to
have a serious network scanner with a permissive license.

The ultimate purpose of this scanner is bruteforcing hosts and ports in search
of running services of a kind.  It should be simple and straight-forward to
either write your own service detection plugins, provided that you're familiar
with writing asynchronous code, or to make changes to the existing ones.

So far there are some problems with reliability, and some clever algorithm to
avoid overloading the network is needed.  Until then, you can use ulimit to cap
the maximum number of concurrent connections.

Packages
--------
Regular releases are sporadic.  git master should be stable enough.  You can get
a package with the latest development version from Archlinux's AUR, or from
openSUSE Build Service for the rest of mainstream distributions.  Consult the
list of repositories and their respective links at:

https://build.opensuse.org/project/repositories/home:pjanouch:git

Building and Usage
------------------
Build dependencies: CMake, pkg-config, help2man +
Runtime dependenices: curses, openssl, Jansson, lua = 5.3 (optional)

 $ git clone --recursive https://github.com/pjanouch/ponymap.git
 $ mkdir ponymap/build
 $ cd ponymap/build
 $ cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug
 $ make

To install the application, you can do either the usual:

 # make install

Or you can try telling CMake to make a package for you.  For Debian it is:

 $ cpack -G DEB
 # dpkg -i ponymap-*.deb

Note that for versions of CMake before 2.8.9, you need to prefix `cpack` with
`fakeroot` or file ownership will end up wrong.

Having the program installed, simply run it with no arguments to retrieve
a usage text.  Have fun scanning.

Author's Notes
--------------
This was quite an interesting project to write and it has taught me a lot about
event loops.  It would be relatively simple to plug in libuv if more robustness
and portability is needed, though.

Contributing and Support
------------------------
Use this project's GitHub to report any bugs, request features, or submit pull
requests.  If you want to discuss this project, or maybe just hang out with
the developer, feel free to join me at irc://irc.janouch.name, channel #dev.

License
-------
'ponymap' is written by Přemysl Janouch <p.janouch@gmail.com>.

You may use the software under the terms of the ISC license, the text of which
is included within the package, or, at your option, you may relicense the work
under the MIT or the Modified BSD License, as listed at the following site:

http://www.gnu.org/licenses/license-list.html
