ponymap
=======

'ponymap' is an experimental network scanner, of alpha quality so far.

Replacing nmap is not the goal, even though it would be rather very nice to
have a serious network scanner with a permissive license.

The ultimate purpose of this scanner is bruteforcing hosts and ports in search
of running services of a kind.  It should be simple and straight-forward to
either write your own service detection plugins, provided that you're familiar
with writing asynchronous code, or to make changes to the existing ones.

So far there are some problems with reliability, and some clever algorithm to
avoid overloading the network is needed.  Until then, you can use ulimit to cap
the maximum number of concurrent connections.

Packages
--------
Regular releases are sporadic.  git master should be stable enough.  You can get
a package with the latest development version from Archlinux's AUR.

Building and Usage
------------------
Build dependencies: CMake >= 3.0, pkg-config, help2man +
Runtime dependenices: curses, openssl, Jansson, lua >= 5.3 (optional)

 $ git clone --recursive https://git.janouch.name/p/ponymap.git
 $ mkdir ponymap/build
 $ cd ponymap/build
 $ cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug
 $ make

To install the application, you can do either the usual:

 # make install

Or you can try telling CMake to make a package for you.  For Debian it is:

 $ cpack -G DEB
 # dpkg -i ponymap-*.deb

Having the program installed, simply run it with no arguments to retrieve
a usage text.  Have fun scanning.

Author's Notes
--------------
This was quite an interesting project to write and it has taught me a lot about
event loops.  It would be relatively simple to plug in libuv if more robustness
and portability is needed, though.

Contributing and Support
------------------------
Use https://git.janouch.name/p/ponymap to report any bugs, request features,
or submit pull requests.  `git send-email` is tolerated.  If you want to discuss
the project, feel free to join me at ircs://irc.janouch.name, channel #dev.

Bitcoin donations are accepted at: 12r5uEWEgcHC46xd64tt3hHt9EUvYYDHe9

License
-------
This software is released under the terms of the 0BSD license, the text of which
is included within the package along with the list of authors.
